db:
   username: "postgres"
   dbname: "postgres"
   sslmode: "disable"
   host: "localhost"
   port: "5428"

server:
   port: ":8030"
   maxHeaderBytes: 1048576
   readTimeout: 10s
   writeTimeout: 10s

handler:
   requestTimeout: 2s
   urlId: "id"